✨ 🚧  WIP convs-mgr blocks and block connections state
italanta/italanta-apps pull request #29
Opened 2022-08-08 15:27 UTC by IanOdhiambo9

# Description

Working on the state management for the frame blocks and block connections.

Issue: [here](https://github.com/italanta/italanta-apps/issues/22).

## Type of change

Please delete options that are not relevant.

- [ ] New feature (non-breaking change which adds functionality)
- [ ] This change requires a documentation update

# Checklist:

- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] My changes generate no new warnings
- [ ] New and existing unit tests pass locally with my changes

2022-08-12 06:21 UTC, jrosseel requested changes

2022-08-12 06:21 UTC, jrosseel commented on apps/conv-learning-manager/src/app/app.module.ts
> +    StroyBlockConnectionsStateModule.forRoot(),
Consider keeping in same state layer as BlockState

2022-08-12 06:21 UTC, jrosseel commented on libs/elements/convs-mgr/controls/input-fields/README.md
> +# elements-convs-mgr-controls-input-fields
Library requires readme.md

@pmutua , we will need a template for README.md's of new NX packages

2022-08-12 06:21 UTC, jrosseel commented on libs/elements/convs-mgr/controls/input-fields/src/lib/components/default-option-field/default-option-field.component.ts
> +    this.inputUniqueId = `default-input-${this.blockFormGroup.value.id}`;
Too long for an ID.

We can save some storage space on the db by just calling this `defo-${...`, short for "default option"

2022-08-12 06:21 UTC, jrosseel commented on libs/elements/convs-mgr/controls/input-fields/src/lib/components/default-option-field/default-option-field.component.ts
> +      this.jsPlumb.addEndpoint(input, {
Eventually will need some factory pattern to centralise jsPlumb add-ons. 
Perhaps in a seperate lib in elements

2022-08-12 06:21 UTC, jrosseel commented on libs/elements/convs-mgr/controls/input-fields/project.json
> +{
I believe this project should be in features under the conv-mgr/library/block-options or something.

This is not really an element as it can only be used in the block editor which is a feature

2022-08-12 06:21 UTC, jrosseel commented on libs/elements/convs-mgr/controls/input-fields/src/lib/components/option-input-field/option-input-field.component.ts
> +    this.inputUniqueId = `input-${this.formGroupNameInput}$-${this.blockFormGroup.value.id}`;
Same comment. Reduce input to `i-....`

2022-08-12 06:21 UTC, jrosseel commented on libs/elements/convs-mgr/controls/input-fields/src/lib/components/option-input-field/option-input-field.component.ts
> +      this.jsPlumb.addEndpoint(input, {
Same comment on the factory

2022-08-12 06:21 UTC, jrosseel commented on libs/features/convs-mgr/stories/blocks/library/src/lib/blocks-library.module.ts
> +import { QuestionsBlockComponent } from './components/questions-block/questions-block.component';
Order of imports. Components before services

2022-08-12 06:21 UTC, jrosseel commented on libs/features/convs-mgr/stories/blocks/library/src/lib/blocks-library.module.ts
> +import { QuestionsBlockComponent } from './components/questions-block/questions-block.component';
Review where QuestionsBlockComponent should be defined. I believe another package because this package is really the bare metal

2022-08-12 06:21 UTC, jrosseel commented on libs/features/convs-mgr/stories/blocks/library/src/lib/blocks-library.module.ts
> +import { QuestionsBlockComponent } from './components/questions-block/questions-block.component';
Watch out for circular dependencies when designing the packages

2022-08-12 06:21 UTC, jrosseel commented on libs/features/convs-mgr/stories/blocks/library/src/lib/components/block/block.component.ts
> +        this.blockFormGroup = _CreateQuestionBlockMessageForm(this._fb, this.block);
Good!

2022-08-12 06:21 UTC, jrosseel commented on libs/features/convs-mgr/stories/blocks/library/src/lib/components/questions-block/questions-block.component.html
> +      Add New Option
Multi lang

2022-08-12 06:21 UTC, jrosseel commented on libs/features/convs-mgr/stories/blocks/library/src/lib/components/questions-block/questions-block.jsplumb.ts
> +export function _QuestionsBlockDecoratePlumb(block: QuestionMessageBlock, comp: ComponentRef<BlockComponent>, jsPlumb: BrowserJsPlumbInstance) : ComponentRef<BlockComponent>
We need to find a clean way to integrate this with the buttons

2022-08-12 06:21 UTC, jrosseel commented on libs/features/convs-mgr/stories/blocks/library/src/lib/model/blocks-forms.model.ts
> +export function _CreateTextMessageBlockForm(_fb: FormBuilder, blockData: TextMessageBlock) {
Add comment on what the function do

2022-08-12 06:21 UTC, jrosseel commented on libs/features/convs-mgr/stories/blocks/library/src/lib/model/blocks-forms.model.ts
> +export function _CreateQuestionBlockMessageForm(_fb: FormBuilder, blockData: QuestionMessageBlock) {
Add comment

2022-08-12 06:21 UTC, jrosseel commented on libs/features/convs-mgr/stories/editor/src/lib/components/blocks-library/blocks-library.component.ts
> +    { id: 'io-block', type: StoryBlockTypes.TextMessage, message: 'Text Block' } as TextMessageBlock,
ID should be different

2022-08-12 06:21 UTC, jrosseel commented on libs/features/convs-mgr/stories/editor/src/lib/model/story-editor-frame.model.ts
> +    await new Promise((resolve) => setTimeout(() => resolve(true), 1000));
Comment out

2022-08-12 06:21 UTC, jrosseel commented on libs/features/convs-mgr/stories/editor/src/lib/model/story-editor-frame.model.ts
> +    let domSourceInputs = Array.from(document.querySelectorAll('input'));
Comment the code. Why are we doing this? And what are we doing

2022-08-12 06:21 UTC, jrosseel commented on libs/features/convs-mgr/stories/editor/src/lib/model/story-editor-frame.model.ts
> +    for(const connection of this._connections) {
Add better comments as "Draw connections".
How does it work? Do we have any reference materials to websites etc?

As you are developing the core machinery of the feature, this needs to be very well documented for others to be able to maintain it

2022-08-12 06:21 UTC, jrosseel commented on libs/features/convs-mgr/stories/editor/src/lib/model/story-editor-frame.model.ts
> +    } as any;
Never do any :O :O :O

2022-08-12 06:21 UTC, jrosseel commented on libs/model/convs-mgr/stories/blocks/messaging/src/lib/question-message-block.interface.ts
> +  options?: ButtonsBlockButton<any>[];
Of type any??

2022-08-12 10:20 UTC, IanOdhiambo9 commented on apps/conv-learning-manager/src/app/app.module.ts
> +    StroyBlockConnectionsStateModule.forRoot(),
I'll leave this out as you had suggested

2022-08-12 10:24 UTC, IanOdhiambo9 commented on libs/elements/convs-mgr/controls/input-fields/project.json
> +{
Moved this lib to library/block-options

2022-08-12 10:26 UTC, IanOdhiambo9 commented on libs/elements/convs-mgr/controls/input-fields/src/lib/components/default-option-field/default-option-field.component.ts
> +      this.jsPlumb.addEndpoint(input, {
For this I've created a decorator function in provide that just returns a decorated element for the input fields.

Check it out in library/block-options/providers

2022-08-12 10:27 UTC, IanOdhiambo9 commented on libs/elements/convs-mgr/controls/input-fields/src/lib/components/option-input-field/option-input-field.component.ts
> +      this.jsPlumb.addEndpoint(input, {
same decorator as default input field above

2022-08-12 10:59 UTC, IanOdhiambo9 commented on libs/features/convs-mgr/stories/blocks/library/src/lib/blocks-library.module.ts
> +import { QuestionsBlockComponent } from './components/questions-block/questions-block.component';
moved questions block into library/question-message-block -> [commit](https://github.com/italanta/italanta-apps/commit/98d407dd861bbd3a6402e5a09d896d1718999d23)

moved the text message block into library/text-message-block -> [commit](https://github.com/italanta/italanta-apps/commit/99122de91eaf007acdcecbb239fc7228e4e66499)

2022-08-12 11:03 UTC, IanOdhiambo9 commented on libs/features/convs-mgr/stories/blocks/library/src/lib/components/questions-block/questions-block.component.html
> +      Add New Option
add_circle is the name of the icon, it does not appear in the frontend. Changing the name in translation will crash the mat-icon

2022-08-12 11:11 UTC, IanOdhiambo9 commented on libs/features/convs-mgr/stories/editor/src/lib/model/story-editor-frame.model.ts
> +    await new Promise((resolve) => setTimeout(() => resolve(true), 1000));
Without the await the drawing does not happen since the blocks and inputs are not in view yet.

2022-08-12 11:21 UTC, IanOdhiambo9 commented on libs/features/convs-mgr/stories/editor/src/lib/model/story-editor-frame.model.ts
> +    } as any;
Got it!! : )

2022-08-12 11:21 UTC, IanOdhiambo9 commented on libs/features/convs-mgr/stories/editor/src/lib/model/story-editor-frame.model.ts
> +    } as any;
fixed as well

2022-08-12 11:29 UTC, IanOdhiambo9 commented on libs/model/convs-mgr/stories/blocks/messaging/src/lib/question-message-block.interface.ts
> +  options?: ButtonsBlockButton<any>[];
Probably written some bad code for this one, there could be a better way to do it. -> [commit](https://github.com/italanta/italanta-apps/commit/9538e05bcc8f1163f4aace65c0d84c8b845e7b77)

2022-08-12 11:30 UTC, IanOdhiambo9 commented on libs/features/convs-mgr/stories/blocks/library/src/lib/components/questions-block/questions-block.jsplumb.ts
> +export function _QuestionsBlockDecoratePlumb(block: QuestionMessageBlock, comp: ComponentRef<BlockComponent>, jsPlumb: BrowserJsPlumbInstance) : ComponentRef<BlockComponent>
sure

2022-08-23 06:24 UTC, jrosseel requested changes
Some small change requests.

The biggest concern is on saving connections. We should override the "addMultiple" with a strategy which avoids duplicate creation of connections

2022-08-23 06:24 UTC, jrosseel commented on apps/conv-learning-manager/src/app/app.module.ts
> +import { StroyBlockConnectionsStateModule } from '@app/state/convs-mgr/stories/block-connections';
Story* note Stroy

2022-08-23 06:24 UTC, jrosseel commented on apps/conv-learning-manager/src/app/app.module.ts
> +    StroyBlockConnectionsStateModule.forRoot(),
Story

2022-08-23 06:24 UTC, jrosseel commented on libs/elements/convs-mgr/controls/input-fields/project.json
> +{
Why does the project still exist then?

2022-08-23 06:24 UTC, jrosseel commented on libs/elements/convs-mgr/controls/input-fields/src/lib/convs-mgr-input-fields.module.ts
> +export class ConvsMgrInputFieldsModule {}
Delete empty module

2022-08-23 06:24 UTC, jrosseel commented on libs/elements/layout/page-convl/src/lib/components/sub-bar/sub-navbar.component.scss
> +  color: purple;
Can this be put in a variable?

2022-08-23 06:24 UTC, jrosseel commented on libs/elements/layout/page-convl/src/lib/components/sub-bar/sub-navbar.component.scss
> +  color: purple;
The color

2022-08-23 06:24 UTC, jrosseel commented on libs/features/convs-mgr/home/src/lib/pages/home/home.page.ts
>  import { NewStoryService } from '../../services/new-story.service';
Order of imports. Local imports should be below lib imports

2022-08-23 06:24 UTC, jrosseel commented on libs/features/convs-mgr/stories/blocks/library/block-options/src/lib/components/default-option-field/default-option-field.component.scss
> +  background-color: rgba($color: #6418C3, $alpha: 0.3);
Can the color be put in scss variable?

2022-08-23 06:24 UTC, jrosseel commented on libs/features/convs-mgr/stories/blocks/library/question-message-block/src/lib/components/questions-block/questions-block.component.html
> +      <mat-icon>add_circle</mat-icon>
Use font awesome

2022-08-23 06:24 UTC, jrosseel commented on libs/features/convs-mgr/stories/blocks/library/text-message-block/src/index.ts
> +export * from './lib/providers/message-block.jsplumb';
jsplumb decorate should be internal

2022-08-23 06:24 UTC, jrosseel commented on libs/features/convs-mgr/stories/blocks/library/text-message-block/src/index.ts
> +export * from './lib/providers/message-block.jsplumb';
Not exported

2022-08-23 06:24 UTC, jrosseel commented on libs/features/convs-mgr/stories/blocks/library/text-message-block/src/lib/providers/message-block.jsplumb.ts
> +import { BlockComponent } from "@app/features/convs-mgr/stories/blocks/library/main";
Watch out for circular deps

2022-08-23 06:24 UTC, jrosseel commented on libs/features/convs-mgr/stories/editor/src/lib/model/story-editor-frame.model.ts
> +    let domSourceInputs = Array.from(document.querySelectorAll('input'));
Move into seperate fn called drawConnections

2022-08-23 06:24 UTC, jrosseel commented on libs/features/convs-mgr/stories/editor/src/lib/model/story-editor-frame.model.ts
> +    this.blocksArray = this._fb.array([]);
Move into seperate fn called drawBlocks

2022-08-23 06:24 UTC, jrosseel commented on libs/features/convs-mgr/stories/editor/src/lib/pages/story-editor/story-editor.page.ts
> +    let connections = this.frame.getJsPlumbConnections as any[];
Where do you get the "getJsPlumbConnections" from?

2022-08-23 06:24 UTC, jrosseel commented on libs/state/convs-mgr/stories/block-connections/src/lib/services/block-connections.service.ts
> +    this._connections$$.addMultiple(connections as StoryBlockConnection[], true).subscribe();
Does this avoid duplicates? 
E.g. when loading then saving

2022-08-25 07:18 UTC, IanOdhiambo9 commented on libs/elements/layout/page-convl/src/lib/components/sub-bar/sub-navbar.component.scss
> +  color: purple;
Done.
I've added a _variables file in libs/elements/theming
I've also updated the project.json with "stylePreprocessorOptions" to include paths for theming files in style.scss.
Now colors and font style groups can be stored in variables.

2022-08-25 07:27 UTC, IanOdhiambo9 commented on libs/features/convs-mgr/stories/blocks/library/block-options/src/lib/components/default-option-field/default-option-field.component.scss
> +  background-color: rgba($color: #6418C3, $alpha: 0.3);
Yes, I've changed to the variables primary purple as was updated in the designs.

2022-08-25 09:21 UTC, IanOdhiambo9 commented on libs/features/convs-mgr/stories/blocks/library/text-message-block/src/lib/providers/message-block.jsplumb.ts
> +import { BlockComponent } from "@app/features/convs-mgr/stories/blocks/library/main";
Handled ,I've moved back the block decorator function for both blocks to the blocks component

2022-08-25 09:32 UTC, IanOdhiambo9 commented on libs/features/convs-mgr/stories/editor/src/lib/pages/story-editor/story-editor.page.ts
> +    let connections = this.frame.getJsPlumbConnections as any[];
On the story editor frame model I have a getter that returns a jsPlumb "getConnections()" method. Calling this getter provides all the active connections hence can be used for fetching new and deleted ones as well.

2022-08-25 09:34 UTC, IanOdhiambo9 commented on libs/state/convs-mgr/stories/block-connections/src/lib/services/block-connections.service.ts
> +    this._connections$$.addMultiple(connections as StoryBlockConnection[], true).subscribe();
I've updated this by moving the logic to the editor state service.
You can check the _determineConnectiontions() and fetchNewJsPlumbCOnnections() which returns all new connections. Therefore the service above only gets called whenever the are new connections only

2022-08-25 09:41 UTC, merged