Sidemenu
italanta/italanta-apps pull request #33
Opened 2022-08-15 14:35 UTC by meshack34

# Description

Please include a summary of the changes and the related issue. Please also include relevant motivation and context. List any dependencies that are required for this change.

Reference the issue related to this PR as shown below. Every issue has it's own number you can find the issue numbers [here](https://github.com/italanta/italanta-apps/issues).

Fixes # (issue) - *Example*: Fixes #10, #20 NOTE: GitHub issue numbers should be prefixed with **#** to aid with issue tracking.

## Type of change

Please delete options that are not relevant.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

# Screenshot (optional)

# How Has This Been Tested?

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration

- [ ] Test A
- [ ] Test B

**Test Configuration**: (optional)
* Firmware version:
* Hardware:
* Toolchain:
* SDK:

# Checklist:

- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules

2022-08-16 09:09 UTC, jrosseel requested changes

2022-08-16 09:09 UTC, jrosseel commented on libs/elements/layout/page-convl/src/lib/components/convl-sidemenu/convl-sidemenu.component.html
> +  Responsive side navigation
What is the meaning of the text "Responsive side navigation" ?

2022-08-16 09:09 UTC, jrosseel commented on libs/elements/layout/page-convl/src/lib/components/convl-sidemenu/convl-sidemenu.component.html
> +        main
Please keep calling it Home in line with design

2022-08-16 09:09 UTC, jrosseel commented on libs/elements/layout/page-convl/src/lib/components/convl-sidemenu/convl-sidemenu.component.html
> -    <!-- Section Chats -->
Don't remove these comments for later reference

2022-08-16 09:09 UTC, jrosseel commented on libs/elements/layout/page-convl/src/lib/convl-page.module.ts
> +import { MatToolbarModule } from '@angular/material/toolbar';
These modules are already a part of MaterialDesignModule hence don't need to be imported

2022-08-17 05:47 UTC, meshack34 commented
yes, Working on it

On Tue, Aug 16, 2022 at 12:09 PM Jente Rosseel ***@***.***>
wrote:

> ***@***.**** requested changes on this pull request.
> ------------------------------
>
> In
> libs/elements/layout/page-convl/src/lib/components/convl-sidemenu/convl-sidemenu.component.ts
> <https://github.com/italanta/italanta-apps/pull/33#discussion_r946521555>:
>
> >
>  import { SubSink } from 'subsink';
>
> +import { BreakpointObserver } from ***@***.***/cdk/layout';
>
> Please removed unused imports
> ------------------------------
>
> In
> libs/elements/layout/page-convl/src/lib/components/convl-sidemenu/convl-sidemenu.component.html
> <https://github.com/italanta/italanta-apps/pull/33#discussion_r946522563>:
>
> > @@ -1,3 +1,16 @@
> +<mat-toolbar class="mat-elevation-z8">
> +  <button
> +    mat-icon-button
> +    *ngIf="sidenav.mode === 'over'"
> +    (click)="sidenav.toggle()"
> +  >
> +    <mat-icon *ngIf="!sidenav.opened"> menu </mat-icon>
> +    <mat-icon *ngIf="sidenav.opened"> close </mat-icon>
> +  </button>
> +  Responsive side navigation
>
> Please use font-awesome and not
>
> Fontawesome:
> ------------------------------
>
> In
> libs/elements/layout/page-convl/src/lib/components/convl-sidemenu/convl-sidemenu.component.html
> <https://github.com/italanta/italanta-apps/pull/33#discussion_r946522879>:
>
> > @@ -1,3 +1,16 @@
> +<mat-toolbar class="mat-elevation-z8">
> +  <button
> +    mat-icon-button
> +    *ngIf="sidenav.mode === 'over'"
> +    (click)="sidenav.toggle()"
> +  >
> +    <mat-icon *ngIf="!sidenav.opened"> menu </mat-icon>
> +    <mat-icon *ngIf="sidenav.opened"> close </mat-icon>
> +  </button>
> +  Responsive side navigation
>
> What is the meaning of the text "Responsive side navigation" ?
> ------------------------------
>
> In
> libs/elements/layout/page-convl/src/lib/components/convl-sidemenu/convl-sidemenu.component.html
> <https://github.com/italanta/italanta-apps/pull/33#discussion_r946523121>:
>
> > @@ -32,7 +45,7 @@
>
>        <div fxLayout="row">
>          <i matListIcon class="fas fa-home list-icon"></i>
> -        Home
> +        main
>
> Please keep calling it Home in line with design
> ------------------------------
>
> In
> libs/elements/layout/page-convl/src/lib/components/convl-sidemenu/convl-sidemenu.component.html
> <https://github.com/italanta/italanta-apps/pull/33#discussion_r946523309>:
>
> > @@ -47,81 +60,7 @@
>        </div>
>      </div>
>
> -    <!-- Section Chats -->
>
> Don't remove these comments for later reference
> ------------------------------
>
> In libs/elements/layout/page-convl/src/lib/convl-page.module.ts
> <https://github.com/italanta/italanta-apps/pull/33#discussion_r946523763>:
>
> > @@ -14,6 +14,13 @@ import { SubNavBarComponent } from './components/sub-bar/sub-navbar.component';
>  import { ConvlNavbarComponent } from './components/convl-navbar/navbar.component';
>
>
> +import { MatToolbarModule } from ***@***.***/material/toolbar';
>
> These modules are already a part of MaterialDesignModule hence don't need
> to be imported
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/italanta/italanta-apps/pull/33#pullrequestreview-1073758041>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AJ6BEOFVIVOLI7QBYWOWJHTVZNLERANCNFSM56SOAEEA>
> .
> You are receiving this because you authored the thread.Message ID:
> ***@***.***>
>

2022-08-21 11:35 UTC, closed without merging