#20 feat[Application design]: Layout of a bot overview:
italanta/italanta-apps pull request #39
Opened 2022-08-23 11:41 UTC by trevin-livele

# Description

The issue #20 requires one to make the application have a good user interface that enables one to view and manage his/her bots easily from the dashboard.with regards to the issue i have edited the user interface in accordance to the design.

I have also added the image Field and the description in the story-section interface.

## Enhancement of the previous user interface to a better one in accordance to the design provided
## Previous Screenshot design

<img width="1185" alt="old" src="https://user-images.githubusercontent.com/60538411/186630276-ce2d08b1-f026-4b07-a768-898dfb857a1a.png">

## Current Screenshot
![Screenshot from 2022-08-23 14-24-40](https://user-images.githubusercontent.com/60538411/186629103-98f6e611-9d21-4fe9-8c55-9f1cf7d906c1.png)

# Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] Any dependent changes have been merged and published in downstream modules

2022-08-23 12:51 UTC, pmutua commented on libs/model/convs-mgr/stories/main/src/lib/story-section.interface.ts
> + }
✅  **Story** interface model extended as per requirement and included a **description** and **image** field

2022-08-23 13:26 UTC, pmutua commented on libs/features/convs-mgr/home/src/lib/pages/home/home.page.scss
> +    background-color: #FFAB2D;
Use re-usable [scss variables](https://sass-lang.com/documentation/variables)

2022-08-23 13:34 UTC, pmutua commented on libs/features/convs-mgr/home/src/lib/components/story-list-item/story-list-item.component.scss
>  }
Add a meaningful class name `.example-card` this will be confusing in the future for other devs.

2022-08-23 13:36 UTC, pmutua commented on libs/features/convs-mgr/home/src/lib/components/story-list-item/story-list-item.component.scss
> +}
Add re-usable [scss variables](https://sass-lang.com/documentation/variables) especially on the colors. I've added a link for reference

2022-08-23 13:47 UTC, pmutua commented on libs/features/convs-mgr/home/src/lib/components/story-list-item/story-list-item.component.html
> +  <mat-card class="example-card">
♻️ Rename .css class name **example** to something meaningful

2022-08-23 13:59 UTC, pmutua requested changes
@trevin-livele there are a couple things we missed out here  from the checklist below the last two:
```markdown
[x] Extend the "Story" interface model to include a description and image field
[x] Implement the design by extending and modifying the components in the feature package (ref _libs/features/convs-mgr/home_)
[x] When doing so, you'll need to create some new child-components of story-list-item
[ ] You will also want to create a new component story-list and move the state layer touchpoint their (= the import of StoriesStore). Remove that import from the home component.
[ ] Use reusable css variables
```

2022-08-24 12:12 UTC, pmutua commented on libs/features/convs-mgr/home/src/lib/components/story-list/story-list.component.ts
> +  constructor(private _stories$$: StoriesStore,private _router: Router) {
add spacing between the injected items in the constructor after comma

i.e `private _stories$$: StoriesStore, private _router: Router`

2022-08-24 12:13 UTC, pmutua commented on libs/features/convs-mgr/home/src/lib/pages/home/home.page.html
> +
✅ ok

2022-08-24 12:13 UTC, pmutua commented on libs/features/convs-mgr/home/src/lib/pages/home/home.page.scss
> +    background-color: mat-color($mat-ele, A200);
✅ ok

2022-08-24 12:14 UTC, pmutua commented on libs/model/convs-mgr/stories/main/src/lib/story-section.interface.ts
> + }
✅ok

2022-08-24 12:14 UTC, pmutua commented on libs/features/convs-mgr/home/src/lib/pages/home/home.page.html
> +    <div class="bot-selector" fxLayout="row wrap" fxLayoutAlign="" fxLayoutGap="26px grid">
✅ ok

2022-08-24 12:17 UTC, pmutua commented on libs/features/convs-mgr/home/src/lib/components/story-list-item/story-list-item.component.html
> +</div>
✅ ok

2022-08-24 12:19 UTC, pmutua commented on libs/elements/theming/common.theme.scss
> +  A900: #6418C3,
✅ ok

2022-08-24 12:21 UTC, pmutua commented on apps/conv-learning-manager/project.json
>            "fileReplacements": [
@trevin-livele why did you change this?

2022-08-24 12:24 UTC, pmutua requested changes
@trevin-livele I have added some comments please check  😉

2022-08-25 06:54 UTC, pmutua requested changes
lets leave the budgets to 1mb

2022-08-25 16:52 UTC, trevin-livele commented on apps/conv-learning-manager/project.json
>            "fileReplacements": [
i have reverted them to the original values

2022-08-26 07:49 UTC, trevin-livele commented
@pmutua i have updated the changes requested and solved the conflict

2022-08-26 12:48 UTC, jrosseel requested changes

2022-08-26 12:48 UTC, jrosseel commented on libs/features/convs-mgr/home/src/lib/components/story-list-item/story-list-item.component.html
> +          {{story.name }} <span class="bot-number">(6 bots)</span>
Needs actual count or to be removed

2022-08-26 14:55 UTC, jrosseel approved these changes

2022-08-26 14:56 UTC, merged