Block layout design#13
italanta/italanta-apps pull request #40
Opened 2022-08-23 18:07 UTC by IanKoech

# Description

Please include a summary of the changes and the related issue. Please also include relevant motivation and context. List any dependencies that are required for this change.

Reference the issue related to this PR as shown below. Every issue has it's own number you can find the issue numbers [here](https://github.com/italanta/italanta-apps/issues).

Fixes # (issue) - *Example*: Fixes #10, #20 NOTE: GitHub issue numbers should be prefixed with **#** to aid with issue tracking.

## Type of change

Please delete options that are not relevant.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

# Screenshot (optional)

# How Has This Been Tested?

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration

- [ ] Test A
- [ ] Test B

**Test Configuration**: (optional)
* Firmware version:
* Hardware:
* Toolchain:
* SDK:

# Checklist:

- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules

2022-08-24 12:26 UTC, pmutua commented
@IanKoech please edit this pr details this is just a template you have added. There is no explanation of what you were covering

2022-08-24 13:04 UTC, pmutua requested changes

2022-08-24 13:04 UTC, pmutua commented on package.json
> +    "bootstrap": "^5.2.0",
@IanKoech I'm afraid that we don't need bootstrap because we are using angular material. the implementation can still be done with angular material.

2022-08-25 06:59 UTC, jrosseel commented
Closed due to use of bootstrap. 

Bootstrap not allowed

2022-08-25 06:59 UTC, closed without merging

2022-08-26 07:31 UTC, IanKoech commented on libs/elements/layout/page-convl/src/lib/components/convl-navbar/navbar.component.html
>  </nav>
@pmutua , Can I update the `story-block.interface.ts` file in order to add the blockIcon and blockTitle properties ?